### ISSUE TITLE
Can't run Server/Client Only tests and can't integrate with Travis-CI

### ISSUE THREAD

**Issue by MarceloPrado** [meteortesting/meteor-mocha#28] opened 2017-05-02 23:30 UTC
I'am trying to integrate my Meteor project into Travis CI. I've tried using `practicalmeteor`, but couldn't make it work on my console. Then, I've discovered `meteor-mocha` and everything worked out just fine on my console. 

I'am having problems, though, with the `TEST_CLIENT=0` command. **It doesn't seem to change anything. My test script runs both on client and server**.

Test script: `"cli-test": "TEST_BROWSER_DRIVER=chrome meteor test TEST_CLIENT=0 --driver-package dispatch:mocha --once --settings settings-development.json"`

It can be run like this: `npm run cli-test`. Although the console prints the script like I've written, `meteor-mocha` seems to ignore that and runs the tests on both platforms. **The tests are executed correctly**, without logging errors.

I'am trying to run server-only because I can't get Travis CI to work. Maybe the error showed bellow is related to client-testing on Travis. It keeps exiting with code 1 when Meteor is about to start. 

**Travis Logs**
``` 
W20170502-23:20:40.330(0)? (STDERR) packages/modules.js:36207
W20170502-23:20:40.400(0)? (STDERR)   static createSession(...args) {}
W20170502-23:20:40.401(0)? (STDERR)                        ^^^
W20170502-23:20:40.401(0)? (STDERR) 
W20170502-23:20:40.402(0)? (STDERR) SyntaxError: Unexpected token ...
W20170502-23:20:40.403(0)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170502-23:20:40.403(0)? (STDERR)     at /tmp/meteor-test-runh7fby/.meteor/local/build/programs/server/boot.js:289:30
W20170502-23:20:40.404(0)? (STDERR)     at Array.forEach (native)
W20170502-23:20:40.404(0)? (STDERR)     at Function._.each._.forEach (/home/travis/.meteor/packages/meteor-tool/.1.4.2_3.15i544++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170502-23:20:40.405(0)? (STDERR)     at /tmp/meteor-test-runh7fby/.meteor/local/build/programs/server/boot.js:128:5
W20170502-23:20:40.405(0)? (STDERR)     at /tmp/meteor-test-runh7fby/.meteor/local/build/programs/server/boot.js:344:5
W20170502-23:20:40.405(0)? (STDERR)     at Function.run (/tmp/meteor-test-runh7fby/.meteor/local/build/programs/server/profile.js:480:12)
W20170502-23:20:40.406(0)? (STDERR)     at /tmp/meteor-test-runh7fby/.meteor/local/build/programs/server/boot.js:343:11
=> Started your app.
=> App running at: http://localhost:3000/
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.10.3/bin/node" "/home/travis/.nvm/versions/node/v6.10.3/bin/npm" "run" "cli-test"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! application-name@1.0.0 cli-test: `TEST_BROWSER_DRIVER=chrome meteor test TEST_CLIENT=0 --driver-package dispatch:mocha --once --settings settings-development.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the application-name@1.0.0 cli-test script 'TEST_BROWSER_DRIVER=chrome meteor test TEST_CLIENT=0 --driver-package dispatch:mocha --once --settings settings-development.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     TEST_BROWSER_DRIVER=chrome meteor test TEST_CLIENT=0 --driver-package dispatch:mocha --once --settings settings-development.json
npm [0mERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs application-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/MarceloPrado/laPag/npm-debug.log
The command "npm run cli-test" exited with 1.
cache.2
store build cache
0.01s
12.73snothing changed, not updating cache
Done. Your build exited with 1.
```

**Mine travis.yml**

```sudo: false

language: node_js
node_js:
  - "6"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Add meteor to path (instead of asking for sudo in the Travis container)
  # We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
  - "npm install"

cache:
  directories:
    - node_modules

before_script:
  - "export PATH=$HOME/.meteor:$PATH"

script:
  - "npm run cli-test"
```

Sorry for writing two issues on one post, I didn't know if they related somehow.

Thanks for attention!

**Comment by aldeed** [comment] 2017-05-04 15:52
@MarceloPrado First thing to try is use Node 4 instead of 6 because there could be differences with the `npm install` command. And/or change that to `meteor npm install` to use the Node version bundled with Meteor.

You may also want to NOT cache `node_modules` for now, at least until you get things working, because caching may hide whether different approaches truly work, unless you're diligent about clearing the Travis cache.

Beyond that, are you using the latest version of dispatch:mocha?

This could be a bug in the pkg, but it would be good to address these things first.

**Comment by MarceloPrado** [comment] 2017-05-05 11:47
Hi @aldeed, thanks for your help.

I've tried using node 4 instead of 6. But same error!
My travis.yml:

```sudo: false

language: node_js
node_js:
  - "4"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Add meteor to path (instead of asking for sudo in the Travis container)
  # We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/

before_script:
  - "export PATH=$HOME/.meteor:$PATH"
  - 'meteor npm install'

script:
  - "npm run cli-test"
```
Strange thing happening: on another computer, terminal logs the same problem. Maybe is related to current node version?
Meteor node version: v4.6.2
OSX node version: v6.10.3

And yes, I'am using the latest `meteor-mocha` version (0.4.1)

Full log trace:
```
npm run cli-test

> application-name@1.0.0 cli-test /Users/Marcelo/portalLaPag
> TEST_BROWSER_DRIVER=chrome meteor test --driver-package dispatch:mocha --once --settings settings-development.json

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> A patch (Meteor 1.4.2.7) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
W20170505-08:46:33.265(-3)? (STDERR) packages/modules.js:36207
W20170505-08:46:33.466(-3)? (STDERR)   static createSession(...args) {}
W20170505-08:46:33.467(-3)? (STDERR)                        ^^^
W20170505-08:46:33.467(-3)? (STDERR) 
W20170505-08:46:33.468(-3)? (STDERR) SyntaxError: Unexpected token ...
W20170505-08:46:33.468(-3)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170505-08:46:33.468(-3)? (STDERR)     at /private/var/folders/34/2jc_cm4s36zbhb9dfxjgtlg40000gn/T/meteor-test-run85h4a8/.meteor/local/build/programs/server/boot.js:289:30
W20170505-08:46:33.469(-3)? (STDERR)     at Array.forEach (native)
W20170505-08:46:33.470(-3)? (STDERR)     at Function._.each._.forEach (/Users/Marcelo/.meteor/packages/meteor-tool/.1.4.2_3.1vo8q2j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170505-08:46:33.471(-3)? (STDERR)     at /private/var/folders/34/2jc_cm4s36zbhb9dfxjgtlg40000gn/T/meteor-test-run85h4a8/.meteor/local/build/programs/server/boot.js:128:5
W20170505-08:46:33.471(-3)? (STDERR)     at /private/var/folders/34/2jc_cm4s36zbhb9dfxjgtlg40000gn/T/meteor-test-run85h4a8/.meteor/local/build/programs/server/boot.js:344:5
W20170505-08:46:33.472(-3)? (STDERR)     at Function.run (/private/var/folders/34/2jc_cm4s36zbhb9dfxjgtlg40000gn/T/meteor-test-run85h4a8/.meteor/local/build/programs/server/profile.js:480:12)
W20170505-08:46:33.473(-3)? (STDERR)     at /private/var/folders/34/2jc_cm4s36zbhb9dfxjgtlg40000gn/T/meteor-test-run85h4a8/.meteor/local/build/programs/server/boot.js:343:11
=> Started your app.

=> App running at: http://localhost:3000/

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/Marcelo/.nvm/versions/node/v6.10.3/bin/node" "/Users/Marcelo/.nvm/versions/node/v6.10.3/bin/npm" "run" "cli-test"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! application-name@1.0.0 cli-test: `TEST_BROWSER_DRIVER=chrome meteor test --driver-package dispatch:mocha --once --settings settings-development.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the application-name@1.0.0 cli-test script 'TEST_BROWSER_DRIVER=chrome meteor test --driver-package dispatch:mocha --once --settings settings-development.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     TEST_BROWSER_DRIVER=chrome meteor test --driver-package dispatch:mocha --once --settings settings-development.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs application-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Marcelo/portalLaPag/npm-debug.log

```

**Comment by aldeed** [comment] 2017-05-09 00:34
@MarceloPrado Does the error really happen differently when using `TEST_CLIENT=0` vs. when you don't? Based on the error it almost looks more like an issue of your app or one of your packages missing a dependency on the `ecmascript` package.

If you are able to make a simple app that reproduces the issue and post a link, it will be much easier to debug.

**Comment by MarceloPrado** [comment] 2017-05-31 14:04
Hi @aldeed, sorry for the delay.

I've created a simple repo for demo. 

Here it is:
https://github.com/MarceloPrado/dispatch-mocha-test

I can run on my terminal, but can't make it work on Travis CI.  Hope you can help me out!
Thanks

**Comment by AbdelMounhim** [comment] 2017-06-20 11:43
Hi,
i have the same problem. 
node 6.6
and it doesn't run on my terminal even without TEST_CLIENT=0

meteor test --driver-package dispatch:mocha
=> Started proxy.                             
=> Meteor 1.5 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
W20170620-13:46:28.337(2)? (STDERR) packages/modules.js:696
W20170620-13:46:28.381(2)? (STDERR)   static createSession(...args) {}
W20170620-13:46:28.382(2)? (STDERR)                        ^^^
W20170620-13:46:28.382(2)? (STDERR) 
W20170620-13:46:28.382(2)? (STDERR) SyntaxError: Unexpected token ...
W20170620-13:46:28.382(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170620-13:46:28.383(2)? (STDERR)     at /private/var/folders/p1/r1t7r7c12wb_4s803skl38p00000gr/T/meteor-test-run15wtver/.meteor/local/build/programs/server/boot.js:297:30
W20170620-13:46:28.383(2)? (STDERR)     at Array.forEach (native)
W20170620-13:46:28.383(2)? (STDERR)     at Function._.each._.forEach (/Users/dev/.meteor/packages/meteor-tool/.1.4.4_1.15qb7y5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170620-13:46:28.383(2)? (STDERR)     at /private/var/folders/p1/r1t7r7c12wb_4s803skl38p00000gr/T/meteor-test-run15wtver/.meteor/local/build/programs/server/boot.js:128:5
W20170620-13:46:28.383(2)? (STDERR)     at /private/var/folders/p1/r1t7r7c12wb_4s803skl38p00000gr/T/meteor-test-run15wtver/.meteor/local/build/programs/server/boot.js:352:5
W20170620-13:46:28.383(2)? (STDERR)     at Function.run (/private/var/folders/p1/r1t7r7c12wb_4s803skl38p00000gr/T/meteor-test-run15wtver/.meteor/local/build/programs/server/profile.js:510:12)
W20170620-13:46:28.384(2)? (STDERR)     at /private/var/folders/p1/r1t7r7c12wb_4s803skl38p00000gr/T/meteor-test-run15wtver/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1

**Comment by aldeed** [comment] 2017-06-20 19:42
@MarceloPrado @AbdelMounhim The readme command was missing the `-E` (fixed now) so I think your projects have a newer version of `selenium-webdriver` that doesn't work properly on Node 4. Run this to fix:

```
meteor npm i -E --save-dev selenium-webdriver@3.0.0-beta-2
```

Make sure the dependency version in package.json is "3.0.0-beta-2", no `^` before it or anything else.

**Closed by aldeed** 2017-06-20 19:42 UTC

**Comment by AbdelMounhim** [comment] 2017-06-21 05:15
thanks @aldeed  it works !
as you guess, **selenium-webdriver 3.0.0-beta-2** works with my node version (v6.11.0) and meteor 1.5
but not  **selenium-webdriver 3.4.0**

**Comment by rooch84** [comment] 2017-10-20 11:03
As someone who also had the `packages/modules.js - static createSession(...args) {} - ^^^` error, i can firm that using `selenium-webdriver 3.0.0-beta-2` also fixes the error.  Will we be able to use the latest version once we switch to Meteor 1.6?

**Comment by leosco** [comment] 2017-10-24 01:59
@aldeed wow, just came across this thread, thanks so much for pointing out that `selenium-webdriver` was the culprit. I'd all but given up on my testing since the error was being thrown even when not using `dispatch:mocha`, but the normal `practicalmeteor:mocha` driver-package.
